// Competitor comparison data for /compare/ and /alternatives/ pages

export const competitors = {
  churnkey: {
    name: 'Churnkey',
    slug: 'churnkey',
    tagline: 'AI-powered cancel flows',
    website: 'https://churnkey.co',
    pricing: {
      label: '$250–$825/mo',
      entry: 250,
      notes: 'Based on MRR. Free trial available.',
    },
    founded: '2021',
    description: 'Churnkey is a popular churn prevention platform offering AI-powered cancel flows, pause offers, and failed payment recovery. It integrates with Stripe and a handful of other payment processors.',
    strengths: [
      'Polished UI and onboarding',
      'AI-generated cancel flow suggestions',
      'Good Stripe integration',
      'Established customer base',
    ],
    weaknesses: [
      'Expensive — starts at $250/mo',
      'Per-MRR pricing scales poorly',
      'Closed source, black-box logic',
      'Limited customization for developers',
      'No free tier',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: true },
      pauseOffers: { churnrecovery: true, them: true },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: true },
      customBranding: { churnrecovery: true, them: 'Paid plans only' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: 'Limited' },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Stripe only' },
      a_bTesting: { churnrecovery: true, them: 'Higher tier only' },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'Churnkey is a solid product, but its pricing makes it inaccessible for early-stage SaaS companies. ChurnRecovery delivers comparable cancel flow intelligence at $20/month — dramatically cheaper while keeping your margins intact as you grow.',
  },

  profitwell: {
    name: 'ProfitWell Retain',
    slug: 'profitwell',
    tagline: 'Failed payment recovery + churn reduction',
    website: 'https://www.profitwell.com/retain',
    pricing: {
      label: 'Performance-based (% of recovered revenue)',
      entry: 0,
      notes: 'ProfitWell Retain charges a percentage of recovered revenue. No fixed price.',
    },
    founded: '2012',
    description: 'ProfitWell Retain (now part of Paddle) is a churn reduction tool focused on dunning and failed payment recovery. It uses benchmarked messaging sequences to recover failed charges.',
    strengths: [
      'Performance-based pricing (no fixed cost)',
      'Large dataset for benchmarking',
      'Strong dunning capabilities',
      'Part of Paddle ecosystem',
    ],
    weaknesses: [
      'Takes % of every recovered dollar — cost scales up',
      'Less focus on voluntary cancel flows',
      'Complex pricing model',
      'Limited developer customization',
      'Paddle ecosystem lock-in',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: 'Basic' },
      pauseOffers: { churnrecovery: true, them: false },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: 'Benchmark-based' },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: 'Limited' },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Paddle-first' },
      a_bTesting: { churnrecovery: true, them: false },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'ProfitWell Retain excels at dunning but charges a percentage of every recovered dollar — meaning your cost grows as you succeed. ChurnRecovery is a flat $20/month with no performance tax, so 100% of your recovered revenue stays in your pocket.',
  },

  churnbuster: {
    name: 'Churn Buster',
    slug: 'churnbuster',
    tagline: 'Failed payment recovery for Stripe',
    website: 'https://churnbuster.io',
    pricing: {
      label: '$149–$299/mo',
      entry: 149,
      notes: 'Fixed monthly pricing based on Stripe MRR.',
    },
    founded: '2016',
    description: 'Churn Buster is a Stripe-focused dunning tool that specializes in recovering failed payments through smart retry logic and email sequences. It is narrowly focused on involuntary churn.',
    strengths: [
      'Best-in-class Stripe dunning',
      'Smart retry logic',
      'Clean email sequences',
      'Simple setup',
    ],
    weaknesses: [
      'Stripe-only',
      'No voluntary cancel flow tools',
      'No pause or discount offers',
      'Relatively expensive for what it does',
      'No developer API',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: false },
      pauseOffers: { churnrecovery: true, them: false },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: false },
      analytics: { churnrecovery: true, them: 'Basic' },
      multiplePaymentProcessors: { churnrecovery: true, them: false },
      a_bTesting: { churnrecovery: true, them: false },
      webhooks: { churnrecovery: true, them: 'Basic' },
    },
    verdict: 'Churn Buster is focused and does dunning well — but it starts at $149/mo and does nothing about voluntary cancellations. ChurnRecovery handles both voluntary churn and failed payments at $20/month — dramatically cheaper with broader coverage.',
  },

  stunning: {
    name: 'Stunning',
    slug: 'stunning',
    tagline: 'Dunning and failed payment recovery',
    website: 'https://stunning.co',
    pricing: {
      label: '$50–$200/mo',
      entry: 50,
      notes: 'Tiered pricing based on recovered revenue or subscriber count.',
    },
    founded: '2014',
    description: 'Stunning is a dunning tool for Stripe-based businesses that helps recover failed payments through smart email sequences and in-app messaging. It is one of the older tools in this space.',
    strengths: [
      'Affordable entry price',
      'Good email templates',
      'SMS notifications',
      'Long track record',
    ],
    weaknesses: [
      'Stripe-only',
      'No cancel flow features',
      'Dated UI',
      'Limited analytics',
      'Still costs money',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: false },
      pauseOffers: { churnrecovery: true, them: false },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: 'Basic' },
      analytics: { churnrecovery: true, them: 'Basic' },
      multiplePaymentProcessors: { churnrecovery: true, them: false },
      a_bTesting: { churnrecovery: true, them: false },
      webhooks: { churnrecovery: true, them: false },
    },
    verdict: 'Stunning handles dunning at an accessible price point, but it lacks any cancel flow tools and is Stripe-only. For comprehensive churn recovery across voluntary and involuntary churn at $20/month, ChurnRecovery is the clear choice.',
  },

  baremetrics: {
    name: 'Baremetrics',
    slug: 'baremetrics',
    tagline: 'SaaS analytics + churn recovery',
    website: 'https://baremetrics.com',
    pricing: {
      label: '$108–$469/mo',
      entry: 108,
      notes: 'Recover is an add-on. Priced based on MRR.',
    },
    founded: '2013',
    description: 'Baremetrics is primarily a SaaS analytics platform. It offers "Recover" — a dunning and cancel flow tool as an add-on. It is best known for its metrics dashboard, not churn recovery.',
    strengths: [
      'Excellent SaaS metrics dashboard',
      'Good Stripe integration',
      'Established brand',
      'Recover includes basic cancel flows',
    ],
    weaknesses: [
      'Expensive if you only want churn recovery',
      'Analytics platform first — churn recovery is secondary',
      'Recover is a paid add-on',
      'No developer API for cancel flows',
      'Limited customization',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: 'Add-on cost' },
      pauseOffers: { churnrecovery: true, them: 'Limited' },
      failedPaymentRecovery: { churnrecovery: true, them: 'Add-on' },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: 'Analytics only' },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Stripe-first' },
      a_bTesting: { churnrecovery: true, them: false },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'Baremetrics is an analytics tool first. If you need churn recovery, you pay extra for a tacked-on feature. ChurnRecovery is purpose-built for churn prevention at $20/month — dramatically cheaper and a better choice for teams that want to stop churn, not just measure it.',
  },

  raaft: {
    name: 'Raaft',
    slug: 'raaft',
    tagline: 'Cancel flow optimization for Shopify',
    website: 'https://raaft.io',
    pricing: {
      label: '$19–$99/mo',
      entry: 19,
      notes: 'Shopify app pricing. Additional fees for advanced features.',
    },
    founded: '2019',
    description: 'Raaft is a Shopify-focused app that helps reduce subscription cancellations through optimized cancel flows and retention offers. It specializes in e-commerce subscription businesses.',
    strengths: [
      'Deep Shopify integration',
      'E-commerce focused features',
      'Affordable entry pricing',
      'Good for subscription box businesses',
    ],
    weaknesses: [
      'Shopify-only platform',
      'No SaaS or general subscription support',
      'Limited analytics',
      'E-commerce focused (not B2B SaaS)',
      'Basic failed payment recovery',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: true },
      pauseOffers: { churnrecovery: true, them: true },
      failedPaymentRecovery: { churnrecovery: true, them: 'Basic' },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: 'Shopify only' },
      analytics: { churnrecovery: true, them: 'Basic' },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Shopify payments' },
      a_bTesting: { churnrecovery: true, them: 'Limited' },
      webhooks: { churnrecovery: true, them: 'Shopify only' },
    },
    verdict: 'Raaft is excellent for Shopify-based subscription businesses but completely unusable for SaaS companies. If you\'re building a B2B SaaS tool, ChurnRecovery provides the flexibility and integrations you need across all payment platforms.',
  },

  prosperstack: {
    name: 'ProsperStack',
    slug: 'prosperstack',
    tagline: 'Cancel flow and retention platform',
    website: 'https://prosperstack.com',
    pricing: {
      label: '$99–$499/mo',
      entry: 99,
      notes: 'Tiered pricing based on subscription volume. Enterprise plans available.',
    },
    founded: '2020',
    description: 'ProsperStack is a cancel flow and subscriber retention platform built for SaaS companies. It offers customizable cancel flows, offer libraries, and analytics to help businesses understand why customers leave.',
    strengths: [
      'Highly customizable cancel flows',
      'Good analytics and exit survey data',
      'No-code flow builder',
      'Solid Stripe and Recurly integrations',
    ],
    weaknesses: [
      'Starts at $99/mo — costly for small teams',
      'No free tier available',
      'Pricing scales steeply with subscriber count',
      'Limited failed payment recovery features',
      'Overkill for solopreneurs and small newsletters',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: true },
      pauseOffers: { churnrecovery: true, them: true },
      failedPaymentRecovery: { churnrecovery: true, them: 'Limited' },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: true },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: true },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Stripe & Recurly' },
      a_bTesting: { churnrecovery: true, them: 'Higher tiers only' },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'ProsperStack is a capable retention platform, but its $99/mo entry price and steep scaling costs make it a poor fit for newsletter creators, coaches, and early-stage SaaS founders. ChurnRecovery delivers the same cancel flow power — cancel flows, pause offers, A/B testing — at $20/month, dramatically cheaper at any scale.',
  },

  recurly: {
    name: 'Recurly Retain',
    slug: 'recurly',
    tagline: 'Enterprise subscription billing + retention',
    website: 'https://recurly.com',
    pricing: {
      label: '$249–$1,000+/mo',
      entry: 249,
      notes: 'Recurly billing starts at ~$249/mo. Retain features are bundled or add-on depending on plan. Enterprise pricing is custom.',
    },
    founded: '2009',
    description: 'Recurly is an enterprise subscription billing and management platform. Recurly Retain is its built-in churn reduction module, offering cancel flow management, dunning, and revenue recovery — but the full platform is designed for mid-market and enterprise businesses, not small subscription operators.',
    strengths: [
      'Mature, enterprise-grade billing platform',
      'Built-in revenue recovery and dunning',
      'Multi-currency and global payment support',
      'Strong analytics and reporting',
    ],
    weaknesses: [
      'Expensive — entry pricing starts at $249+/mo',
      'Designed for enterprise, overkill for small businesses',
      'Complex setup and onboarding',
      'Retain features require Recurly as your full billing platform',
      'No free tier — no way to trial without commitment',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: true },
      pauseOffers: { churnrecovery: true, them: 'Limited' },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: true },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Recurly-first' },
      a_bTesting: { churnrecovery: true, them: 'Enterprise only' },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'Recurly Retain is a capable enterprise tool — but you\'re paying $249–$1,000+/mo for a billing platform you may not need just to access the retention features. ChurnRecovery gives you the cancel flow, exit survey, and pause offer functionality for $20/month, and works alongside your existing Stripe setup without replacing it.',
  },

  zuora: {
    name: 'Zuora',
    slug: 'zuora',
    tagline: 'Enterprise subscription management platform',
    website: 'https://zuora.com',
    pricing: {
      label: 'Custom — typically $1,000–$5,000+/mo',
      entry: 0,
      notes: 'Zuora does not publish pricing. Enterprise contracts typically start at $1,000–$5,000+/mo based on transaction volume and modules.',
    },
    founded: '2007',
    description: 'Zuora is a large enterprise subscription management platform serving Fortune 500 companies. It handles billing, revenue recognition, subscription analytics, and has retention modules — but the platform is designed for companies with complex enterprise billing needs, large engineering teams, and multi-year contracts.',
    strengths: [
      'Industry-leading enterprise billing capabilities',
      'Deep revenue recognition and compliance features',
      'Handles extremely complex subscription models',
      'Established platform used by major enterprises',
    ],
    weaknesses: [
      'Very expensive — enterprise pricing, often $1,000–$5,000+/mo',
      'Requires months of implementation and dedicated engineering',
      'Massively over-engineered for small businesses',
      'No self-serve or quick-start option',
      'Retention features secondary to billing complexity',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: 'Enterprise module' },
      pauseOffers: { churnrecovery: true, them: 'Complex setup required' },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Dev work required' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: true },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: true },
      a_bTesting: { churnrecovery: true, them: 'Custom development' },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'Zuora is built for enterprises with dedicated billing engineering teams, complex compliance requirements, and Fortune 500 contracts. If you\'re a newsletter creator, coach, or small SaaS founder, Zuora is simply not for you. ChurnRecovery is $20/month, no-code, and live in 15 minutes.',
  },

  brightback: {
    name: 'Brightback (Chargebee)',
    slug: 'brightback',
    tagline: 'Acquired cancel flow tool — now part of Chargebee',
    website: 'https://www.chargebee.com/retain',
    pricing: {
      label: '$299–$999+/mo (as part of Chargebee Retain)',
      entry: 299,
      notes: 'Brightback was acquired by Chargebee in 2021. Pricing is now bundled into Chargebee Retain — meaning you need a full Chargebee subscription to access it. Costs have increased significantly since acquisition.',
    },
    founded: '2018',
    description: 'Brightback was an independent cancel flow and retention platform, founded in 2018 and acquired by Chargebee in 2021. It was well-regarded for its no-code cancel flow builder and behavioral targeting. Since the acquisition, the product has been folded into Chargebee Retain — requiring the full Chargebee billing platform to use, and pricing has increased substantially.',
    strengths: [
      'Originally strong no-code cancel flow builder',
      'Behavioral targeting for offer personalization',
      'Good analytics and exit survey data',
      'Now part of a mature enterprise billing platform',
    ],
    weaknesses: [
      'No longer available as a standalone product',
      'Acquired by Chargebee — pricing has increased significantly',
      'Requires full Chargebee platform commitment',
      'Original indie/SaaS-friendly pricing is gone',
      'Overkill and expensive for small subscription businesses',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: 'Chargebee subscription required' },
      pauseOffers: { churnrecovery: true, them: 'Chargebee subscription required' },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: true },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Chargebee-first' },
      a_bTesting: { churnrecovery: true, them: 'Enterprise only' },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'Brightback used to be a great independent cancel flow tool. Then Chargebee acquired it. Now you can only access Brightback\'s features by purchasing the full Chargebee platform at $299–$999+/mo. If you liked what Brightback originally offered — affordable, standalone cancel flows — ChurnRecovery is what Brightback used to be: focused, independent, and dramatically cheaper at $20/month.',
  },

  'paddle-retain': {
    name: 'Paddle Retain',
    slug: 'paddle-retain',
    tagline: 'Churn recovery built into the Paddle payment ecosystem',
    website: 'https://www.paddle.com/retain',
    pricing: {
      label: 'Performance-based (% of recovered revenue)',
      entry: 0,
      notes: 'Paddle Retain is bundled with ProfitWell Retain (acquired by Paddle in 2022). It charges a percentage of recovered revenue — no fixed fee, but costs grow with your success. Only available to Paddle-billed businesses.',
    },
    founded: '2012',
    description: 'Paddle Retain (formerly ProfitWell Retain) is a churn recovery tool available to businesses that use Paddle as their payment processor. After Paddle acquired ProfitWell in 2022, Retain became a core part of Paddle\'s merchant-of-record billing ecosystem. It focuses on dunning and failed payment recovery for Paddle-billed businesses, but it is not available to Stripe users.',
    strengths: [
      'Included with Paddle billing — no extra signup needed',
      'Large benchmark dataset for email timing',
      'Good dunning capabilities for Paddle sellers',
      'No fixed monthly cost',
    ],
    weaknesses: [
      'Only available if you use Paddle for billing',
      'Not compatible with Stripe — Stripe sellers cannot use it',
      'Takes a percentage cut of every recovered dollar',
      'Weak cancel flow features compared to dedicated tools',
      'Moving from Paddle to Stripe means losing Retain entirely',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: 'Basic, Paddle only' },
      pauseOffers: { churnrecovery: true, them: false },
      failedPaymentRecovery: { churnrecovery: true, them: 'Paddle only' },
      aiSuggestions: { churnrecovery: true, them: 'Benchmark-based' },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: 'Limited' },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Paddle only' },
      a_bTesting: { churnrecovery: true, them: false },
      webhooks: { churnrecovery: true, them: 'Paddle only' },
    },
    verdict: 'Paddle Retain is only useful if you\'re already using Paddle and plan to stay on Paddle forever. If you use Stripe — or want the flexibility to switch — Paddle Retain simply doesn\'t work for you. ChurnRecovery is $20/month, built for Stripe-first businesses, and works with any Stripe-powered subscription tool (Substack, Kajabi, Ghost, Memberful, and more). Zero platform lock-in, zero percentage fees.',
  },

  'stripe-billing': {
    name: 'Stripe Billing',
    slug: 'stripe-billing',
    tagline: 'Stripe\'s built-in dunning — but no cancel flow',
    website: 'https://stripe.com/billing',
    pricing: {
      label: '0.5–0.8% of billing volume',
      entry: 0,
      notes: 'Stripe Billing charges 0.5% on invoices if you use Stripe Billing features. The dunning/retry logic is included. There is no additional cost for smart retries, but there is no cancel flow feature at all.',
    },
    founded: '2011',
    description: 'Stripe Billing is the subscription and invoicing layer built into Stripe. It includes smart payment retry logic (dunning) to recover failed payments automatically. What it does not include is any cancel flow tooling — when a customer clicks "Cancel Subscription," Stripe just cancels it. No save offer, no pause option, no discount prompt. ChurnRecovery adds the cancel flow layer on top of Stripe Billing.',
    strengths: [
      'Already built into Stripe — no extra tool needed',
      'Smart retry logic for failed payments',
      'Reliable and trusted infrastructure',
      'No separate account required',
      'Handles invoicing and subscription management',
    ],
    weaknesses: [
      'Zero cancel flow capability — customers cancel instantly',
      'No pause offers, discount prompts, or save flows',
      'No exit surveys or churn reason tracking',
      'No A/B testing for retention offers',
      'Addresses only involuntary churn (failed payments)',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: false },
      pauseOffers: { churnrecovery: true, them: false },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: false },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: 'Partial (billing % fee)' },
      developerAPI: { churnrecovery: true, them: true },
      analytics: { churnrecovery: true, them: 'Basic' },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Stripe only' },
      a_bTesting: { churnrecovery: true, them: false },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'Stripe Billing is excellent infrastructure and you should absolutely use it — but it does not stop subscribers from cancelling. When a customer hits "Cancel," Stripe cancels them. That\'s lost revenue you\'ll never get back. ChurnRecovery plugs directly into Stripe for $20/month and intercepts the cancellation moment with a save flow: a pause offer, a discount, a downgrade option. Use Stripe Billing as your billing engine, and add ChurnRecovery on top to recover the subscribers Stripe would otherwise lose.',
  },

  chargebee: {
    name: 'Chargebee Retain',
    slug: 'chargebee',
    tagline: 'Subscription billing with churn recovery add-on',
    website: 'https://www.chargebee.com/retain',
    pricing: {
      label: '$299–$999+/mo',
      entry: 299,
      notes: 'Retain is an add-on to Chargebee subscription billing. Full platform pricing is separate.',
    },
    founded: '2011',
    description: 'Chargebee Retain is the churn recovery module built on top of Chargebee\'s subscription billing platform. It offers cancel flow management, dunning, and customer retention workflows — but requires the full Chargebee platform to use.',
    strengths: [
      'Deep integration with Chargebee billing',
      'Enterprise-grade feature set',
      'Multi-currency and global billing support',
      'Mature product with a large user base',
    ],
    weaknesses: [
      'Requires Chargebee subscription — expensive lock-in',
      'Retain is a paid add-on on top of already-high platform costs',
      'Overwhelming complexity for small businesses',
      'Not suitable for teams outside the Chargebee ecosystem',
      'Minimum spend easily exceeds $500/mo all-in',
    ],
    features: {
      cancelFlows: { churnrecovery: true, them: 'Add-on cost' },
      pauseOffers: { churnrecovery: true, them: true },
      failedPaymentRecovery: { churnrecovery: true, them: true },
      aiSuggestions: { churnrecovery: true, them: false },
      customBranding: { churnrecovery: true, them: 'Limited' },
      openSource: { churnrecovery: true, them: false },
      freeTier: { churnrecovery: '30-day free trial', them: false },
      developerAPI: { churnrecovery: true, them: true },
      analytics: { churnrecovery: true, them: true },
      multiplePaymentProcessors: { churnrecovery: true, them: 'Chargebee-first' },
      a_bTesting: { churnrecovery: true, them: 'Enterprise only' },
      webhooks: { churnrecovery: true, them: true },
    },
    verdict: 'Chargebee Retain is a powerful enterprise tool, but you\'re paying $300–$1,000+/mo just to access churn features that require already having Chargebee as your billing platform. ChurnRecovery works with any payment processor at $20/month — making it the obvious choice for lean teams who want results without the enterprise price tag.',
  },
}

export const featureLabels = {
  cancelFlows: 'Cancel flow builder',
  pauseOffers: 'Pause / snooze offers',
  failedPaymentRecovery: 'Failed payment recovery',
  aiSuggestions: 'AI-powered suggestions',
  customBranding: 'Custom branding',
  openSource: 'Open source',
  freeTier: 'Free tier',
  developerAPI: 'Developer API',
  analytics: 'Analytics dashboard',
  multiplePaymentProcessors: 'Multiple payment processors',
  a_bTesting: 'A/B testing',
  webhooks: 'Webhooks',
}

export function getCompetitor(slug) {
  return competitors[slug] || null
}

export function getAllCompetitorSlugs() {
  return Object.keys(competitors)
}

export function getFeatureValue(val) {
  if (val === true) return { type: 'yes', label: 'Yes' }
  if (val === false) return { type: 'no', label: 'No' }
  return { type: 'partial', label: val }
}
